<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;
use App\Models\Cuisine;
use Carbon\Carbon;
use Cviebrock\EloquentSluggable\Services\SlugService;

class CuisinesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        // static data cuisines
        DB::table('cuisines')->insert([
            //
            ['name'=>'American Food','slug' => SlugService::createSlug(Cuisine::class, 'slug','American Food')  ,'description'=>'American cuisine is the cooking style and traditional dishes prepared in the United States. It has been significantly influenced by European, indigenous Native Americans, African Americans, Asians, Pacific Islanders, and many other cultures and traditions.','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'Cajun Food' ,'slug' => SlugService::createSlug(Cuisine::class, 'slug','Cajun Food') ,'description'=>'Cajun cuisine is a style of cooking originating in Louisiana, mainly from the Acadian (Cajun) area of the state (the "Acadian triangle", ranging from western Texas to eastern Mississippi, with the north point being mid-Louisiana). While it is similar to Louisiana Creole cuisine in that it has adapted to local ingredients, and while there are many overlapping dishes, such as gumbo, it differs in its cooking style -- Creole tends to use classical French cooking techniques, whereas Cajun tends to use rustic, provincial French cooking techniques.','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'Caribbean Cuisine','slug' => SlugService::createSlug(Cuisine::class, 'slug','Caribbean Cuisine')  ,'description'=>'Caribbean cuisine is a fusion of African,[1] Creole, Cajun, Amerindian, European, Latin American, Indian/South Asian, Afghan, Middle Eastern, and Chinese. These traditions were brought from many different countries when they came to the Caribbean.[1] In addition, the population has created styles that are unique to the region.','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'Chinese Cuisine','slug' => SlugService::createSlug(Cuisine::class, 'slug','Chinese Cuisine')  ,'description'=>'Chinese cuisine is an important part of Chinese culture and includes cuisines originating from China. Because of the Chinese diaspora and historical power of the country, Chinese cuisine has influenced many other cuisines in Asia and beyond, with modifications made to cater to local palates. Chinese food staples such as rice, soy sauce, noodles, tea, chili oil, and tofu, and utensils such as chopsticks and the wok, can now be found worldwide.','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'French Cuisine' ,'slug' => SlugService::createSlug(Cuisine::class, 'slug','French Cuisine') ,'description'=>'French cuisine (French: Cuisine française) consists of the cooking traditions and practices from France. Its cuisine has been influenced throughout the centuries by the many surrounding cultures of Spain, Italy, Switzerland, Germany and Belgium, in addition to its own food traditions on the long western coastlines of the Atlantic, the Channel and inland.','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'German Food','slug' => SlugService::createSlug(Cuisine::class, 'slug','German Food')  ,'description'=>'The cuisine of Germany (German: Deutsche Küche) is made up of many different local or regional cuisines, reflecting the country\'s federal history. Germany itself is part of the larger cultural region of Central Europe, sharing many culinary traditions with neighbouring countries such as Poland and the Czech Republic. Southern regions, like Bavaria and Swabia, share dishes with Austrian cuisine and parts of Swiss cuisine.','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'Greek Food','slug' => SlugService::createSlug(Cuisine::class, 'slug','Greek Food')  ,'description'=>'Greek cuisine (Greek: Ελληνική Κουζίνα) is the cuisine of Greece and the Greek diaspora.[2] In common with many other cuisines of the Mediterranean, it is founded on the triad of wheat, olive oil, and wine.[3] It uses vegetables, olive oil, grains, fish, and meat, including pork, poultry, veal and beef, lamb, rabbit, and goat. Other important ingredients include pasta (for example hilopites), cheeses, lemon juice, herbs, olives, and yogurt. Bread made of wheat is ubiquitous; other grains, notably barley, are also used, especially for paximathia. Common dessert ingredients include nuts, honey, fruits, and filo pastries. It continues traditions from Ancient Greek and Byzantine cuisine, while incorporating Balkan and Italian influences.','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'Hungarian Cuisine','slug' => SlugService::createSlug(Cuisine::class, 'slug','Hungarian Cuisine')  ,'description'=>'Hungarian or Magyar cuisine is the cuisine characteristic of the nation of Hungary and its primary ethnic group, the Magyars. Traditional Hungarian dishes are primarily based on meats, seasonal vegetables, fruits, bread, and dairy products','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'Indian Cuisine' ,'slug' => SlugService::createSlug(Cuisine::class, 'slug','Indian Cuisine') ,'description'=>'Indian cuisine consists of a variety of regional and traditional cuisines native to the Indian subcontinent. Given the diversity in soil, climate, culture, ethnic groups, and occupations, these cuisines vary substantially and use locally available spices, herbs, vegetables, and fruits.','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'Italian Food' ,'slug' => SlugService::createSlug(Cuisine::class, 'slug','Italian Food') ,'description'=>'Italian cuisine (Italian: Cucina italiana, pronounced [kuˈtʃiːna itaˈljaːna]) is a Mediterranean cuisine[1] consisting of the ingredients, recipes and cooking techniques developed across the Italian Peninsula since antiquity, and later spread around the world together with waves of Italian diaspora.Significant changes occurred with the colonization of the Americas and the introduction of potatoes, tomatoes, capsicums, maize and sugar beet — the latter introduced in quantity in the 18th century. It is one of the best known and most appreciated gastronomies worldwide.','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'Japanese Food','slug' => SlugService::createSlug(Cuisine::class, 'slug','Japanese Food')  ,'description'=>'Japanese cuisine encompasses the regional and traditional foods of Japan, which have developed through centuries of political, economic, and social changes. The traditional cuisine of Japan (Japanese: washoku) is based on rice with miso soup and other dishes; there is an emphasis on seasonal ingredients. Side dishes often consist of fish, pickled vegetables, and vegetables cooked in broth. Seafood is common, often grilled, but also served raw as sashimi or in sushi. Seafood and vegetables are also deep-fried in a light batter, as tempura. Apart from rice, a staple includes noodles, such as soba and udon. Japan also has many simmered dishes, such as fish products in broth called oden, or beef in sukiyaki and nikujaga.','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'Lebanese Cuisine','slug' => SlugService::createSlug(Cuisine::class, 'slug','Lebanese Cuisine')  ,'description'=>'Lebanese cuisine is the culinary traditions and practices originating from Lebanon. It includes an abundance of whole grains, fruits, vegetables, fresh fish and seafood. Poultry is eaten more often than red meat, and when red meat is eaten, it is usually lamb and goat meat. Dishes include copious amounts of garlic and olive oil, and dishes are often seasoned with lemon juice. Chickpeas and parsley are also staples of the Lebanese diet','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name' => 'Middle Eastern Cuisine','slug' => SlugService::createSlug(Cuisine::class, 'slug','Middle Eastern Cuisine')   ,'description' => 'Middle Eastern cuisine or West Asian cuisine includes Arab, Armenian, Assyrian, Azerbaijani, Cypriot, Egyptian, Georgian, Iranian, Iraqi, Israeli, Kurdish, Lebanese, Palestinian and Turkish cuisines. Common ingredients include olives and olive oil, pitas, honey, sesame seeds, dates,[1] sumac, chickpeas, mint, rice and parsley, and popular dishes include kebabs, dolmas, falafel, baklava, yogurt, doner kebab, shawarma and mulukhiyah.','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'Mediterranean Cuisine','slug' => SlugService::createSlug(Cuisine::class, 'slug','Mediterranean Cuisine')  ,'description'=>'Mediterranean cuisine is the food and methods of preparation used by the people of the Mediterranean Basin. The idea of a Mediterranean cuisine originates with the cookery writer Elizabeth David\'s book, A Book of Mediterranean Food (1950) and was amplified by other writers working in English.','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'Mexican Cuisine','slug' => SlugService::createSlug(Cuisine::class, 'slug','Mexican Cuisine')  ,'description'=>'Mexican cuisine consists of the cooking cuisines and traditions of the modern country of Mexico. Its earliest roots lie in Mesoamerican cuisine. Its ingredients and methods begin with the first agricultural communities such as the Maya who domesticated maize, created the standard process of maize nixtamalization, and established their foodways (Maya cuisine).[2] Successive waves of other Mesoamerican groups brought with them their own cooking methods. These included: the Olmec, Teotihuacanos, Toltec, Huastec, Zapotec, Mixtec, Otomi, Purépecha, Totonac, Mazatec, Mazahua, and Nahua. With the Mexica formation of the multi-ethnic Triple Alliance (Aztec Empire), culinary foodways became infused (Aztec cuisine).','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'Moroccan Cuisine','slug' => SlugService::createSlug(Cuisine::class, 'slug','Moroccan Cuisine')  ,'description'=>'Moroccan cuisine is influenced by Morocco\'s interactions and exchanges with other cultures and nations over the centuries.Moroccan cuisine is usually a mix of Amazigh, Southern Saharan, Arab, Andalusian, and Mediterranean cuisines, with slight European (French and Spanish) and sub-Saharan influences.','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'Russian Cuisine','slug' => SlugService::createSlug(Cuisine::class, 'slug','Russian Cuisine')  ,'description'=>'Russian cuisine is a collection of the different dishes and cooking traditions of the Russian people as well as a list of culinary products popular in Russia, with most names being known since pre-Soviet times, coming from all kinds of social circles.','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'Spanish Food','slug' => SlugService::createSlug(Cuisine::class, 'slug','Spanish Food')  ,'description'=>'Spanish cuisine (Spanish: Cocina española) consists of the cooking traditions and practices from Spain. Olive oil (of which Spain is the world\'s largest producer) is heavily used in Spanish cuisine.It forms the base of many vegetable sauces (known in Spanish as sofritos).Herbs most commonly used include parsley, oregano, rosemary and thyme.The use of garlic has been noted as "common to all Spanish cooking."The most used meats in Spanish cuisine include chicken, pork, lamb and veal.Fish and seafood are also consumed on a regular basis.','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'Thai Cuisine','slug' => SlugService::createSlug(Cuisine::class, 'slug','Thai Cuisine')  ,'description'=>'Traditional Thai cuisine loosely falls into four cuisines: tom (boiled dishes), yam (spicy salads), tam (pounded foods), and gaeng (curries). Deep-fries, stir-fries, and steamed dishes derive from Chinese cuisine.','created_at' => Carbon::now(),'updated_at' =>Carbon::now()],
            ['name'=>'Turkish Cuisine','slug' => SlugService::createSlug(Cuisine::class, 'slug','Turkish Cuisine')  ,'description'=>'Turkish cuisine (Turkish: Türk mutfağı) is largely the heritage of Ottoman cuisine, which can be described as a fusion and refinement of Mediterranean, Balkan, Middle Eastern, Central Asian, Eastern European, Armenian, and Georgian cuisines.[1][2][3] Turkish cuisine has in turn influenced those and other neighbouring cuisines, including those of Southeast Europe (Balkans), Central Europe, and Western Europe.[3] The Ottomans fused various culinary traditions of their realm with influences from Mesopotamian cuisine, Greek cuisine, Levantine cuisine, Egyptian cuisine, Balkan cuisine, along with traditional Turkic elements from Central Asia (such as ayran and kaymak), creating a vast array of specialities.','created_at' => Carbon::now(),'updated_at' =>Carbon::now()]

        ]);
    }
}
